typography_spectrum: 0.9531499871518463
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.18320252047851682
  lightness: 0.30452460888773203
  saturation: 0.5397575979586691
  rhythmicContrast: 0.760876226471737
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23388442490249872
analytics:
  google: null
  facebook: null
  twitter: null
name: BrainyDogs
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get BTFD
    url: 'http://bef78ihkiac9u6254xkd5cqc5l.hop.clickbank.net/?tid=GRIDWEB'
    type: external
favicon: null
title: Are you ready to own a genius dog?
description: >-
  Discover  21 FUN and SIMPLE brain games that will transform your dog from
  Amateur to Einstein!
purpose: []
